# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Kvpk"
license = "MIT"
licenselink = "https://github.com/kybervpk"
description = "Site template for KyberVpk"
homepage = "https://kybervpk.fi"
tags = []
features = []
min_version = "0.41"

[author]
  name = ""
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
